
package com.davidoladeji.park.service.implementation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BookingService", targetNamespace = "http://implementation.service.park.davidoladeji.com/", wsdlLocation = "http://localhost:8080/BookingService/BookingServiceImpl?wsdl")
public class BookingService_Service
    extends Service
{

    private final static URL BOOKINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOOKINGSERVICE_EXCEPTION;
    private final static QName BOOKINGSERVICE_QNAME = new QName("http://implementation.service.park.davidoladeji.com/", "BookingService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/BookingService/BookingServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOOKINGSERVICE_WSDL_LOCATION = url;
        BOOKINGSERVICE_EXCEPTION = e;
    }

    public BookingService_Service() {
        super(__getWsdlLocation(), BOOKINGSERVICE_QNAME);
    }

    public BookingService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOOKINGSERVICE_QNAME, features);
    }

    public BookingService_Service(URL wsdlLocation) {
        super(wsdlLocation, BOOKINGSERVICE_QNAME);
    }

    public BookingService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOOKINGSERVICE_QNAME, features);
    }

    public BookingService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookingService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BookingService
     */
    @WebEndpoint(name = "BookingServiceImplPort")
    public BookingService getBookingServiceImplPort() {
        return super.getPort(new QName("http://implementation.service.park.davidoladeji.com/", "BookingServiceImplPort"), BookingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookingService
     */
    @WebEndpoint(name = "BookingServiceImplPort")
    public BookingService getBookingServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://implementation.service.park.davidoladeji.com/", "BookingServiceImplPort"), BookingService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOOKINGSERVICE_EXCEPTION!= null) {
            throw BOOKINGSERVICE_EXCEPTION;
        }
        return BOOKINGSERVICE_WSDL_LOCATION;
    }

}
